variables:
    # we need lower case!!!
    CI_PROJECT_NAMESPACE: docker
    CONTAINER_TEST_IMAGE: docker.rz.tu-harburg.de:5000/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID
    CONTAINER_VERSIONED_IMAGE: docker.rz.tu-harburg.de:5000/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
    CONTAINER_RELEASE_IMAGE: docker.rz.tu-harburg.de:5000/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest

stages:
    - build
    - deploy
    
docker_image:
    stage: build
    only:
        - tags
        - triggers        
        - branches
    tags:
        - build
    script:
        - sudo docker build --no-cache --pull -t $CONTAINER_TEST_IMAGE .
        - sudo docker push $CONTAINER_TEST_IMAGE
        
deploy_latest:
    stage: deploy
    script:
        - sudo docker pull $CONTAINER_TEST_IMAGE
        - sudo docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
        - sudo docker push $CONTAINER_RELEASE_IMAGE
    after_script:
        ## Child Images bauen
        #- curl -X POST -F token=${PROJECT_362_TOKEN} -F ref=${CI_COMMIT_REF_NAME} "https://collaborating.tuhh.de/api/v4/projects/362/trigger/pipeline"
    tags:
        - deploy
    only:
        - master
        
deploy_version:
    stage: deploy
    script:
        - sudo docker pull $CONTAINER_TEST_IMAGE
        - sudo docker tag $CONTAINER_TEST_IMAGE $CONTAINER_VERSIONED_IMAGE
        - sudo docker push $CONTAINER_VERSIONED_IMAGE
    after_script:
        ## Child Images bauen
        #- curl -X POST -F token=${PROJECT_362_TOKEN} -F ref=${CI_COMMIT_REF_NAME} "https://collaborating.tuhh.de/api/v4/projects/362/trigger/pipeline"
    tags:
        - deploy
    only:
        - branches
        - /^.*-release$/
        - /^.*-stable$/
        - /^([0-9]{1,}\.){2,2}[0-9]{1,}/
    except:
        - master